# Generated by Django 5.0.1 on 2024-04-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_question_choice"),
    ]

    operations = [
        migrations.DeleteModel(name="Choice",),
        migrations.DeleteModel(name="Question",),
    ]
